# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Oi < Formula
  desc ""
  homepage ""
  version "0.77.0"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/open-integration/oi/releases/download/v0.77.0/oi_0.77.0_Darwin_x86_64.tar.gz"
    sha256 "90e96dba655d8fa369f3acd334db9fce38956090dc7b7ff1c8d16952865a302b"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/open-integration/oi/releases/download/v0.77.0/oi_0.77.0_Darwin_arm64.tar.gz"
    sha256 "a2b9de60d32bf5f3ab7b18e194926eada1d816b14b9ae81fb03e1aa52e1eac0a"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/open-integration/oi/releases/download/v0.77.0/oi_0.77.0_Linux_x86_64.tar.gz"
    sha256 "e42d501cfa49aa52aa5b485460d3c78440a54747d5c6ca663975c394fff6104e"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/open-integration/oi/releases/download/v0.77.0/oi_0.77.0_Linux_arm64.tar.gz"
    sha256 "72b300a1d6c2981156d973d925688979a5b1bee16e442aba37586b6bc8245729"
  end

  def install
    bin.install "oi"
  end
end
