# This file was generated by GoReleaser. DO NOT EDIT.
class Oictl < Formula
  desc ""
  homepage ""
  version "0.7.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/open-integration/oictl/releases/download/0.7.0/oictl_0.7.0_Darwin_x86_64.tar.gz"
    sha256 "df7120964b375f5ded261a2bb07046e8f4293586666e85a364e9c4d427ebbcd1"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/open-integration/oictl/releases/download/0.7.0/oictl_0.7.0_Linux_x86_64.tar.gz"
      sha256 "0b159cd1f2b67f63aa8dc3accdaba2c3eb973b5c3dfb620947984681f6bddf0a"
    end
  end
  
  depends_on "quicktype"

  def install
    bin.install "program"
  end
end
